spring:
  sql:
    init:
#      schema-locations:
#        - classpath*:db/mysql/member/roles_schema.sql
#        - classpath*:db/mysql/cart_detail/cart_detail_schema.sql
#        - classpath*:db/mysql/cart/cart_schema.sql
#        - classpath*:db/mysql/order_product/order_product_schema.sql
#        - classpath*:db/mysql/order/order_schema.sql
#        - classpath*:db/mysql/member/member_schema.sql
#        - classpath*:db/mysql/product/product_schema.sql
#        - classpath*:db/mysql/vegetarian/vegetarian_schema.sql
#        - classpath*:db/mysql/constraint.sql
      data-locations:
        - classpath*:db/mysql/data.sql
      encoding: UTF-8
      mode: always

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true

  datasource:
    password: ${RDS_PASSWORD}
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
  key:
    secret: ${JWT_SECRET_KEY}

mail:
  address:
    admin: ${ADMIN_MAIL}